### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by PopcornPaws** [PopcornPaws/triptych-rs#1]
- [x] add tests and handle unwraps
- [x] add wasm tests for `nodejs` target
- [ ] setup github actions (handle wasm-test errors as well)
- [ ] library cleanup
- [ ] use Borsh instead of json serialization?
- [ ] benchmarking and performance improvements
- [ ] integrate with Metamask Flask (required to access the private key)
- [ ] setup a PLONK-based proof system for `privkey-address` derivation (?) and use addresses in the ring

[Wasm example](https://github.com/piotr-roslaniec/snap-wasm-example) for Metamask Flask. Note, that Metamask Flask is currently only supported in Chrome.

[Another wasm example](https://github.com/MetaMask/snaps-skunkworks/tree/main/packages/examples/examples/wasm)
